openapi: 3.0.0
info:
  title: eformsign API
  version: '1.0'
servers:
  - url: 'http://api.eformsign.com/v2.0'
paths:
  '/api/documents/{DOCUMENT_ID}':
    parameters:
      - schema:
          type: string
        name: DOCUMENT_ID
        in: path
        required: true
    get:
      summary: 문서정보 조회
      tags:
        - eformsign
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 문서 id
                  template:
                    type: object
                    description: 템플릿 정보
                    properties:
                      id:
                        type: string
                        description: 템플릿 id
                      name:
                        type: string
                        description: 템플릿 명
                      document_name:
                        type: string
                        description: 문서 제목
                      document_number:
                        type: string
                        description: 문서 번호
                  creator:
                    type: object
                    description: '문서 생성자 정보(id, name 포함)'
                    properties:
                      id:
                        type: string
                        description: 문서 생성자 id
                      name:
                        type: string
                        description: 생성자 명
                      recipient_type:
                        type: string
                        description: 수신자 타입
                      created_date:
                        type: integer
                        format: int64
                        description: 생성일
                  last_editor:
                    type: object
                    description: '문서 수정자 정보(id, name 포함)'
                    properties:
                      id:
                        type: string
                        description: 수정자 id
                      name:
                        type: string
                        description: 수정자 명
                      recipient_type:
                        type: string
                        description: 수신자 타입
                      updated_date:
                        type: integer
                        format: int64
                        description: 문서 수정일
                  current_status:
                    type: object
                    description: 현재 상태 정보
                    properties:
                      status_type:
                        type: string
                        description: 상태 타입
                      step_type:
                        type: string
                        description: 스탭 타입
                      step_index:
                        type: number
                        description: 스탭 index
                      step_name:
                        type: string
                        description: 스탭 명
                  step_recipients:
                    description: 수신자들 정보
                    type: array
                    items:
                      type: object
                      properties:
                        "recipient_type\t":
                          type: string
                        id:
                          type: string
                        name:
                          type: string
                  fields:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 필드 id
                        value:
                          type: string
                          description: 필드 값
                        type:
                          type: string
                          description: 필드의 데이터 타입
                  previous_status:
                    type: array
                    description: 이전 상태 정보
                    items:
                      type: object
                      properties:
                        step_type:
                          type: string
                          description: 스탭 ㅌ
                        step_name:
                          type: string
                          description: 스탭 명
                        action_type:
                          type: string
                          description: 액션 타입
                        executor:
                          type: object
                          description: 수행자 정보
                          properties:
                            recipient_type:
                              type: string
                              description: 수행자 타입
                            id:
                              type: string
                              description: 수행자 id
                            name:
                              type: string
                              description: 수행자 이름
                            executed_date:
                              type: integer
                              format: int64
                              description: 수행 날짜
                  next_status:
                    type: array
                    description: 다음 상태 정보
                    items:
                      type: object
                      properties:
                        step_type:
                          type: string
                          description: 스탭 타입
                        step_name:
                          type: string
                          description: 스탭 명
                        step_recipients:
                          type: object
                          description: 수신자들 정보
                          properties:
                            recipient_type:
                              type: string
                              description: 수신자 타입
                            id:
                              type: string
                              description: 수신자 id
                            name:
                              type: string
                              description: 수신자 이름
                  histories:
                    type: array
                    description: 히스토리 정보
                    items:
                      type: object
                      properties:
                        step_type:
                          type: string
                          description: 스탭 타입
                        action_type:
                          type: string
                          description: 액션 타입
                        executor:
                          type: object
                          description: 수행자 정보
                          properties:
                            recipient_type:
                              type: string
                              description: 수행자 타입
                            id:
                              type: string
                              description: ''
                            name:
                              type: string
                              format: int64
                              description: 수행자 이름
                            executor_date:
                              type: integer
                              format: int64
                              description: 수행 날짜
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: 에러 코드
                  ErrorMessage:
                    type: string
                    description: 에러 메시지
              examples:
                실패 시:
                  value:
                    code: '4030001'
                    ErrorMessage: invalid api key
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: get-api-documents-DOCUMENT_ID
      description: |-
        문서의 일반정보, 상세정보, 이력, 진행상황 등을 조회합니다.
        *참고: http://wiki.oz4cs.com/display/eformsignapi/2.2.3+Open+API
      parameters:
        - in: unknown
        - schema:
            type: boolean
          in: query
          name: include_fields
          description: 'default는 false, 필요시 true로 요청'
        - schema:
            type: boolean
          in: query
          description: 'default는 false, 필요시 true로 요청'
          name: include_histories
        - schema:
            type: boolean
          in: query
          description: 'default는 false, 필요시 true로 요청'
          name: include_previous_status
        - schema:
            type: boolean
          in: query
          description: 'default는 false, 필요시 true로 요청'
          name: include_next_status
        - schema:
            type: string
          in: header
          name: Content-Type
          required: true
          description: application/json
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer <access_token>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
        description: ''
  /api/documents:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    description: 문서 목록 정보
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 문서 ID
                        template:
                          type: object
                          description: 템플릿 정보
                          properties:
                            id:
                              type: string
                              description: 템플릿 ID
                            name:
                              type: string
                              description: 템플릿 명
                        document_name:
                          type: string
                          description: 문서 제목
                        document_number:
                          type: string
                          description: 문서 번호
                        creator:
                          type: object
                          description: |-
                            문서 생성자 정보
                            문서 생성자 객체(id, name 포함)
                          properties:
                            id:
                              type: string
                              description: 문서 생성자 id
                            name:
                              type: string
                              description: 생성자 명
                            recipient_type:
                              type: string
                              description: 수신자 타입
                        created_date:
                          type: integer
                          description: 생성일
                        last_editor:
                          type: object
                          description: |-
                            문서 수정자 정보
                            문서 수정자 객체(id, name 포함)
                          properties:
                            id:
                              type: string
                              description: 수정자 id
                            name:
                              type: string
                              description: 수정자 이름
                            recipient_type:
                              type: string
                              description: 수신자 타입
                        updated_date:
                          type: string
                          description: 문서 수정일
                        current_status:
                          type: object
                          description: 현재 상태 정보
                          properties:
                            status_type:
                              type: string
                              description: 상태 타입
                            step_type:
                              type: string
                              description: 단계 타입
                        step_index:
                          type: string
                          description: 단계 index
                        step_name:
                          type: string
                          description: 단계 이름
                        step_recipients:
                          type: array
                          description: 수신자 정보
                          items:
                            type: object
                            properties:
                              recipient_type:
                                type: string
                                description: 수신자 타입
                              id:
                                type: string
                                description: 수신자 id
                              name:
                                type: string
                                description: 수신자 이름
                        fields:
                          type: array
                          description: 필드 정보
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                description: 필드 id
                              value:
                                type: string
                                description: 필드 값
                              type:
                                type: string
                                description: 필드 데이터 타입
                        previous_status:
                          type: array
                          description: 이전 상태 정보
                          items:
                            type: object
                            properties:
                              step_type:
                                type: string
                                description: 단계 타입
                              step_name:
                                type: string
                                description: 단계 이름
                              action_type:
                                type: string
                                description: 액션 타입
                              executor:
                                type: object
                                description: 수행자 정보
                                properties:
                                  recipient_type:
                                    type: string
                                    description: 수행자 타입
                                  id:
                                    type: string
                                    description: 수행자 id
                                  name:
                                    type: string
                                    description: 수행자 이름
                              executed_date:
                                type: string
                                description: 수행 날짜
                        next_status:
                          type: array
                          description: 다음 상태 정보
                          items:
                            type: object
                            properties:
                              step_type:
                                type: string
                                description: 단계 타입
                              step_name:
                                type: string
                                description: 단계 이름
                              step_recipients:
                                type: object
                                description: 수신자 정보
                                properties:
                                  recipient_type:
                                    type: string
                                    description: 수신자 타입
                                  id:
                                    type: string
                                    description: 수신자 id
                                  name:
                                    type: string
                                    description: 수신자 이름
                        histories:
                          type: array
                          description: 문서 히스토리 정보
                          items:
                            type: object
                            properties:
                              step_type:
                                type: string
                                description: 단계 타입
                              action_type:
                                type: string
                                description: 액션 타입
                              executor:
                                type: object
                                description: 수행자 정보
                                properties:
                                  recipient_type:
                                    type: string
                                    description: 수행자 타입
                                  id:
                                    type: string
                                    description: 수행자 id
                                  name:
                                    type: string
                                    description: 수행자 이름
                              executed_date:
                                type: string
                                description: 수행 날짜
                  total_rows:
                    type: integer
                    description: 전체 문서 수
                  limit:
                    type: integer
                    description: 한 페이지에 표시되는 문서 수
                  skip:
                    type: integer
                    description: 건너뛴 문서 수
              examples:
                example-1:
                  value:
                    documents:
                      - null
                    id:
                      - string
                    '': string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시됨
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
      operationId: get-api-documents
      description: |-
        문서의 일반 정보, 상세 정보, 이력, 진행상황 등을 목록으로 조회할 수 있는 API입니다.
        * 도메인은 Access Token 발급 시 반환되는 api_key.company.api_url 값을 사용해야 합니다. 
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Access token값을 Bearer 토큰으로 사용
          required: true
        - schema:
            type: boolean
          in: query
          name: include_fields
          description: '필드 포함 여부/default는 false, 필요시 true로 요청'
        - schema:
            type: boolean
          in: query
          name: include_histories
          description: '문서 이력 포함 여부/default는 false, 필요시 true로 요청'
        - schema:
            type: boolean
          in: query
          name: include_previous_status
          description: '이전 단계 정보 포함 여부/default는 false, 필요시 true로 요청'
        - schema:
            type: boolean
          in: query
          name: include_next_status
          description: '다음 단계 정보 포함 여부/default는 false, 필요시 true로 요청'
      requestBody:
        content:
          application/json:
            schema:
              type:
                - object
                - string
              properties:
                type:
                  type: string
                  description: '문서함 타입/01:진행 중, 02:처리할 문서, 03: 완료 문서'
                title_and_content:
                  type: string
                  description: '문서 제목 및 내용에서 검색할 쿼리/입력 시, 검색 결과에 해당하는 문서만 표시'
                title:
                  type: string
                  description: '문서 제목에서 검색할 쿼리/입력 시, 검색 결과에 해당하는 문서만 표시'
                content:
                  type: string
                  description: '문서 내용에서 검색할 쿼리/입력 시, 검색 결과에 해당하는 문서만 표시'
                limit:
                  type: string
                  description: 한 번에 표시할 문서 수/페이징 용
                skip:
                  type: string
                  description: |-
                    목록에서 건너뛰고 표시할 문서 수
                    ex) limit을 20으로 설정한 경우, skip = 0 : 1page, 20 : 2page, 40 : 3page와 같이 페이징할 수 있음. limit의 배수가 아니더라도 설정 가능
        description: ''
    delete:
      summary: ''
      operationId: delete-api-documents
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: |-
                      응답 코드
                      -1: 정상
                  message:
                    type: string
                    description: 메시지
                  status:
                    type: string
                    description: |-
                      HTTP 응답코드
                      200: 정상
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type:
                      - string
                      - object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시됨
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
      description: |-
        도메인은 Access Token 발급 시 반환되는 api_key.company.api_url 값을 사용해야 합니다. 
        https://kr-api.eformsign.com/v2.0/api/documents

        https://kr-api.eformsign.com/v2.0/api/documents?template_id=c4b18b459b1649b286e4955334ed9b50
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Access token값을 Bearer 토큰으로 사용/Bearer<access_token>
          required: true
        - schema:
            type: string
          in: query
          name: template_id
          description: 삭제할 문서의 템플릿 ID
      requestBody:
        content:
          application/json:
            schema:
              type:
                - string
                - object
              properties:
                document_ids:
                  type:
                    - string
                    - array
                  description: 삭제할 문서의 ID를 String 형태로 담고 있는 Array
                  items: {}
        description: '* 형태로 담고 있는 Array DELETE 메서드의 경우, 사용 환경에 따라 Body를 입력하지 못하거나, 입력해도 무시하고 호출하는 경우가 발생할 수 있음'
  /api/members:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  members:
                    type: array
                    description: 멤버 목록
                    items:
                      type:
                        - boolean
                        - string
                        - object
                      properties:
                        withdrawal:
                          type: boolean
                          description: ''
                        id:
                          type: string
                          description: 아이디
                        account_id:
                          type: string
                        name:
                          type: string
                          description: 이름
                        department:
                          type: string
                          description: 부서
                        position:
                          type: string
                          description: 직책
                        create_date:
                          type: integer
                          description: 생성 날짜
                        enabled:
                          type: boolean
                          description: 활성화 여부
                        isRefused:
                          type: boolean
                          description: 초대 거절 여부
                        isExpired:
                          type: boolean
                          description: 초대 만료 여부
                        isInvited:
                          type: boolean
                          description: 초대 여부
                        isWithdrawal:
                          type: boolean
                          description: 멤버 탈퇴 여부
                        contact:
                          type:
                            - string
                            - object
                          description: 연락처 정보
                          properties:
                            country_id:
                              type: string
                              description: 국번
                            number:
                              type: string
                              description: 전화번호
                            tel:
                              type: string
                              description: 휴대전화 번호
                        role:
                          type: array
                          description: 권한 정보
                          items: {}
                        group:
                          type: array
                          description: 그룹 정보
                          items: {}
                        fields:
                          type:
                            - string
                            - object
                          description: 커스텀 필드 정보
                          properties:
                            u_id:
                              type: string
                              description: uid
                            field_key:
                              type: string
                              description: 필드 키
                            field_value:
                              type: string
                              description: 필드 값
                            field_file:
                              type: string
                              description: 필드 파일
                        deleted:
                          type: boolean
                          description: 탈퇴 여부
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시됨
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
      operationId: get-api-members
      description: |-
        회사에 소속된 멤버 목록을 조회합니다. 
        삭제된 멤버를 제외한 활성, 비활성, 탈퇴 멤버의 정보를 포함한 목록을 조회할 수 있습니다.

        *도메인은 Access Token 발급 시 반환되는 api_key.company.api_url 값을 사용해야 합니다. 

        ex)
        https://kr-api.eformsign.com/v2.0/api/members
        https://kr-api.eformsign.com/v2.0/api/members?include_delete=true&eb_name_search=홍길동
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Access token 값을 Bearer 토큰으로 사용/ Bearer <access_token>  '
          required: true
        - schema:
            type: boolean
          in: query
          name: member_all
          description: '전체 멤버 조회 여부/ default는 false, 필요시 true로 요청'
        - schema:
            type: boolean
          in: query
          name: include_field
          description: '구성원 커스텀 필드 포맷 정보 포함 여부/ default는 false, 필요시 true로 요청'
        - schema:
            type: boolean
          in: query
          name: include_delete
          description: '삭제 멤버 조회 여부/ default는 false, 필요시 true로 요청'
        - schema:
            type: string
          in: query
          name: eb_name_search
          description: '입력한 쿼리와 이름(members.name)이 일치하는 구성원 검색/ default는 빈 값, 필요시 입력하여 요청 '
    post:
      summary: ''
      operationId: post-api-members
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  company_id:
                    type: string
                    description: 회사 ID
                  member:
                    type:
                      - string
                      - object
                    description: 멤버 정보
                    properties:
                      name:
                        type: string
                        description: 멤버 이름
                      id:
                        type: string
                        description: 멤버 ID
              examples:
                성공 시:
                  value:
                    company_id: e434785d44604c61b2a24a3a9e94b7c3
                    member:
                      name: test98
                      id: test98@forcs.com
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type:
                      - string
                      - object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시됨
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
              examples:
                실패 시:
                  value:
                    code: '4000135'
                    ErrorMessage: This ID is already taken.
      description: |-
        회사에 멤버를 추가하는 API입니다.
        (forcs_com에 account를 생성하고 지정된 회사에 멤버를 추가하는 API)
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Access token값을 Bearer 토큰으로 사용/ Bearer <access_token>
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type:
                    - string
                    - object
                  description: 계정 정보
                  properties:
                    id:
                      type: string
                      description: 계정으로 사용할 이메일
                    password:
                      type: string
                      description: 비밀번호
                    first_name:
                      type: string
                      description: 사용자 이름
                    contact:
                      type:
                        - string
                        - object
                      description: 사용자 연락처 정보
                      properties:
                        tel:
                          type: string
                          description: 전화번호
                        number:
                          type: string
                          description: 휴대폰 번호
                        country_number:
                          type: string
                          description: |-
                            국가번호
                            "+82"형태로 입력
                    department:
                      type: string
                      description: 부서
                    position:
                      type: string
                      description: 직책
                    agreement:
                      type:
                        - string
                        - object
                      description: 약관
                      properties:
                        marketing:
                          type: string
                          description: 마케팅 정보 수신 동의
                    role:
                      type: array
                      description: |-
                        사용자 권한 정보
                        "company_manager": 회사 관리 권한,"template_manager": 템플릿 관리 권한
                        중복 입력 가능, 미입력 시 member 권한 기본 적용됨
                      items: {}
            examples:
              example-1:
                value:
                  account:
                    id: test98@forcs.com
                    password: '1111'
                    first_name: test98
                    contact:
                      tel: '01023456789'
                      number: '01034567890'
                      country_number: '+82'
                    department: 연구소
                    position: 연구원
                    agreement:
                      marketing: true
                    role:
                      - company_manager
                      - template_manager
    patch:
      summary: ''
      operationId: patch-api-members
      responses:
        '200':
          description: OK
      description: |-
        회사의 멤버를 수정하는 API입니다.

        * 도메인은 Access Token 발급 시 반환되는 api_key.company.api_url 값을 사용해야 합니다. 

        도메인/v2.0/api/members/{member_id}
  '/api/members/{member_id}':
    parameters:
      - schema:
          type: string
        name: member_id
        in: path
        required: true
    get:
      summary: 멤버 수정
      tags: []
      responses: {}
      operationId: get-api-members-member_id
      description: ''
    patch:
      summary: ''
      operationId: patch-api-members-member_id
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  company_id:
                    type: string
                    description: 회사 ID
                  member:
                    type: object
                    description: 멤버 정보
                    properties:
                      name:
                        type: string
                        description: 멤버 이름
                      id:
                        type: string
                        description: 멤버 계정
              examples:
                성공 시:
                  value:
                    company_id: e434785d44604c61b2a24a3a9e94b7c3
                    member:
                      name: 홍길동
                      id: test1@forcs.com
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type:
                      - string
                      - object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시됨
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
              examples:
                실패 시:
                  value:
                    code: '4000074'
                    ErrorMessage: Invalid id or password.
      description: 회사의 멤버를 수정하는 API입니다.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type:
                    - string
                    - object
                  description: 계정 정보
                  properties:
                    id:
                      type: string
                      description: '사용자 계정(이메일), 사용자 조회용'
                    name:
                      type: string
                      description: 사용자 이름
                    contact:
                      type:
                        - string
                        - object
                      description: 사용자 연락처 정보
                      properties:
                        tel:
                          type: string
                          description: 전화번호
                        number:
                          type: string
                          description: 휴대폰 번호
                    department:
                      type: string
                      description: 부서
                    position:
                      type: string
                      description: 직책
                    role:
                      type: array
                      description: |-
                        사용자 권한 정보
                        "company_manager": 회사 관리 권한, "template_manager": 템플릿 관리 권한
                        중복입력 가능, 미입력 시 member 권한 기본 적용
                      items: {}
            examples:
              example:
                value:
                  account:
                    id: test1@forcs.com
                    name: 홍길동
                    enabled: true
                    contact:
                      number: 010-2345-6789
                      tel: 010-1234-5678
                    department: 연구소
                    position: 연구원
                    role:
                      - company_manager
                      - template_manager
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: "application/json\t"
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Access token값을 Bearer 토큰으로 사용, Bearer <access_token>'
          required: true
    delete:
      summary: ''
      operationId: delete-api-members-member_id
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: '응답 코드(-1: 정상)'
                  message:
                    type: string
                    description: 메시지
                  status:
                    type: string
                    description: 'HTTP 응답 코드(200: 정상)'
              examples:
                성공 시:
                  value:
                    code: '-1'
                    message: Completed.
                    status: '200'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type:
                      - string
                      - object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
              examples:
                실패 시:
                  value:
                    code: '4000074'
                    ErrorMessage: Invalid id or password.
      description: |-
        회사 멤버를 삭제하는 API입니다.
        회사 대표관리자가 멤버를 탈퇴시킬 수 있습니다.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Access token값을 Bearer 토큰으로 사용, Bearer <access_token>'
          required: true
  '/api/documents/{document_id}/re_request_outsider':
    parameters:
      - schema:
          type: string
        name: document_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: '응답 코드(-1:정상)'
                  message:
                    type: string
                    description: 메시지
                  status:
                    type: string
                    description: 'HTTP 응답코드(200: 정상)'
              examples:
                성공 시:
                  value:
                    code: '-1'
                    message: Completed.
                    status: '200'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    description: |-
                      에러 상세 정보
                      error의 경우에만 표시, 
                      error 객체(code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
              examples:
                실패 시:
                  value:
                    code: '4000004'
                    ErrorMessage: No document selected.
      operationId: get-api-documents-document_id-re_request_outsider
      description: |-
        외부 수신자에게 요청한 문서를 다시 요청하는 API입니다.

        *도메인은 Access Token 발급 시 반환되는 api_key.company.api_url 값을 사용해야 합니다. 
        ex)
        https://kr-api.eformsign.com/v2.0/api/documents/d803930e2094464aab548c340f7c8a4b/re_request_outsider
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Access token값을 Bearer 토큰으로 사용, Bearer <access_token> '
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type:
                    - string
                    - object
                  properties:
                    next_steps:
                      type: array
                      description: 다음 단계 정보
                      items:
                        type: object
                        properties:
                          step_type:
                            type: string
                            description: |-
                              단계 유형
                              "outsider"
                          approvers:
                            type: array
                            items:
                              type: object
                              properties:
                                seq:
                                  type: integer
                                user_id:
                                  type: string
                                  description: 수신자 이메일
                                user_name:
                                  type: string
                                  description: 수신자 이름
                                code:
                                  type: string
                                  description: |-
                                    국가 코드
                                    "+82" 형태로 입력
                                number:
                                  type: string
                                  description: 핸드폰 번호
                                auth_password:
                                  type: string
                                  description: 비밀번호
                                auth_hint:
                                  type: string
                                  description: 비밀번호 힌트
                                auth_valid_time:
                                  type: integer
                                  description: |-
                                    유효 시간
                                    시간 단위
                                approval_line_name:
                                  type: string
                                  description: 결재선 이름
                                use_mobile_auth:
                                  type: boolean
                                  description: 핸드폰 본인 인증 사용 여부
                                use_mobile_auth_view:
                                  type: boolean
                                unselected_sections:
                                  type: array
                                  items: {}
                          comment:
                            type: string
                            description: 요청 메시지
            examples:
              example-1:
                value:
                  input:
                    next_steps:
                      - step_type: outsider
                        approvers:
                          - seq: 1
                            user_id: test1@forcs.com
                            user_name: 홍길동
                            code: '+82'
                            number: '1022792430'
                            auth_password: forcs
                            auth_hint: 포시에스
                            auth_valid_time: 48
                            approval_line_name: ''
                            use_mobile_auth: false
                            use_mobile_auth_view: false
                            unselected_sections: []
                        comment: 재요청입니다.
  /api/forms:
    get:
      summary: OPA2_015 작성 가능한 템플릿 목록 조회
      tags: []
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json
          content:
            application/json:
              schema:
                type:
                  - object
                  - integer
                properties:
                  total_rows:
                    type: integer
                    description: 템플릿 수
                  templates:
                    type: array
                    description: 템플릿 목록
                    items:
                      type: object
                      properties:
                        form_id:
                          type: string
                          description: 템플릿 ID
                        name:
                          type: string
                          description: 템플릿 이름
                        version:
                          type: string
                          description: 템플릿 버전
                        start_write_date:
                          type: integer
                          description: 템플릿 유효기간-시작일
                        end_write_date:
                          type: integer
                          description: |-
                            템플릿 유효기간-종료일
                            '기간 제한 없음'일 경우 32503647599999 반환
                        unlimited:
                          type:
                            - string
                            - boolean
                          description: 템플릿 유효 기간-기간 제한 없음 여부
                        create_id:
                          type: string
                        create_name:
                          type: string
                        create_date:
                          type: integer
                        update_id:
                          type: string
                        update_name:
                          type: string
                        update_date:
                          type: integer
                        category:
                          type: string
                        keyword:
                          type: string
                        desc:
                          type: string
                        favorite:
                          type: boolean
                        is_sample:
                          type: boolean
                        file:
                          type: object
                          properties:
                            form_image_id:
                              type: string
                            form_files:
                              type: array
                              items:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  ozr_id:
                                    type: string
                                  ext:
                                    type: string
                                  alias:
                                    type: string
                                  file_id:
                                    type: string
              examples:
                성공 시:
                  value:
                    total_rows: 147
                    templates:
                      - form_id: 9e71904bdc0f469a9d3682d7ff3cd62f
                        name: 휴아아하하
                        version: '2'
                        start_write_date: 1534690800000
                        end_write_date: 32503647599999
                        unlimited: true
                        create_id: pks424@forcs.com
                        create_name: 박경석
                        create_date: 1603784046202
                        update_id: pks424@forcs.com
                        update_name: 박경석
                        update_date: 1603862903783
                        category: Sample
                        keyword: ''
                        desc: ''
                        favorite: false
                        is_sample: false
                        file:
                          form_image_id: 0b8061a9abeb4bf5a3ca3f7b67aea9a3
                          form_files:
                            - type: excel
                              ozr_id: ff6d90e063f944ce80563a19b423043f
                              ext: .xlsx
                              alias: 휴가신청서.ozr
                              file_id: ff729f81f1b94728991d098f529796fb
                      - // 중략: null
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    description: |-
                      에러 상세 정보
                      error 의 경우에만 표시
                      error 객체 ( code, message 포함)
                    properties:
                      code:
                        type: string
                        description: 에러 코드
                      message:
                        type: string
                        description: 에러 메시지
              examples:
                실패 시:
                  value:
                    code: '4030001'
                    ErrorMessage: invalid api key
      operationId: get-api-forms
      description: |-
        내부 멤버의 작성가능한 템플릿 목록을 조회하는 API입니다.

        *도메인은 Access Token 발급 시 반환되는 api_key.company.api_url 값을 사용해야 합니다. 
        ex) https://kr-api.eformsign.com/v2.0/api/forms
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Access token값을 Bearer 토큰으로 사용, Bearer <access_token>'
          required: true
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: eformsign
